name: CI

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout repo
      - name: NPM Install
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Svelte Check
        run: |
          npm run check
      - name: Unit and Integration Tests
        run: |
          npm run test:ci
      - name: Acceptance Tests
        run: |
          npx playwright install
          npm run test
      - name: ⏫ Bump package version
        id: bumping-version
        uses: jpb06/bump-package@latest
        with:
          minor-keywords: feat,feature
          should-default-to-patch: true
          commit-user: Sonny Alves Dias
          commit-user-email: sonny@alvesdi.as
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      - name: Trigger Github Actions of parent repo
        run: |
          curl -X POST https://api.github.com/repos/SonnyAD/utile-compose/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u 'Sonny:${{ secrets.ACCESS_TOKEN }}' \
          --data '{"event_type": "deploy-front", "client_payload": { "service": "front" }}'
