# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - name: NPM Install
        run: | 
          npm ci
      - name: Lint
        run: | 
          npm run lint
      - name: Trigger Github Actions of parent repo
        run: |
          curl -X POST https://api.github.com/repos/SonnyAD/utile-compose/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u 'Sonny:${{ secrets.ACCESS_TOKEN }}' \
          --data '{"event_type": "deploy-front", "client_payload": { "service": "front" }}'
