name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repo
      - name: NPM Install
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Svelte Check
        run: |
          npm run check
      - name: Test
        run: |
          npm run test:ci
      - name: Build
        run: |
          npm run build
